# Generated by Django 5.2 on 2025-04-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_land_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='land',
            options={},
        ),
        migrations.RemoveField(
            model_name='land',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='land',
            name='title',
        ),
        migrations.AddField(
            model_name='land',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='land_type',
            field=models.CharField(blank=True, choices=[('agricultural', 'Agricultural'), ('residential', 'Residential'), ('commercial', 'Commercial'), ('natural', 'Natural'), ('resort', 'Resort')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='size',
            field=models.IntegerField(blank=True, help_text='Size in square meters', null=True),
        ),
    ]
