# Generated by Django 5.2 on 2025-04-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_land_options_remove_land_is_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='land_type',
        ),
        migrations.AddField(
            model_name='land',
            name='type',
            field=models.CharField(choices=[('agricultural', 'Agricultural'), ('commercial', 'Commercial'), ('residential', 'Residential'), ('natural', 'Natural'), ('resort', 'Resort')], default='agricultural', max_length=20),
        ),
        migrations.AlterField(
            model_name='land',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='land',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='land',
            name='name',
            field=models.CharField(default='Untitled Land', max_length=100),
        ),
        migrations.AlterField(
            model_name='land',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='land',
            name='size',
            field=models.IntegerField(default=1000, help_text='Size in square meters'),
        ),
    ]
