# Generated by Django 5.2 on 2025-04-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_land_land_type_land_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='name',
        ),
        migrations.RemoveField(
            model_name='land',
            name='type',
        ),
        migrations.AddField(
            model_name='land',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='land',
            name='land_type',
            field=models.CharField(choices=[('Agricultural', 'Agricultural'), ('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Natural', 'Natural'), ('Resort', 'Resort')], default='Agricultural', max_length=20),
        ),
        migrations.AddField(
            model_name='land',
            name='title',
            field=models.CharField(default='Land Property', max_length=100),
        ),
        migrations.AlterField(
            model_name='land',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='land_images/'),
        ),
        migrations.AlterField(
            model_name='land',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='land',
            name='size',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Size in square meters', max_digits=10),
        ),
    ]
