# Generated by Django 5.2 on 2025-04-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_land_name_remove_land_type_land_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('farmer', 'Farmer'), ('landowner', 'Landowner'), ('admin', 'Admin')], default='buyer', max_length=20),
        ),
    ]
