# Generated by Django 4.2.7 on 2025-04-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='lease_terms',
            field=models.CharField(blank=True, help_text='Comma-separated lease terms', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='price_per_acre',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='land',
            name='soil_type',
            field=models.CharField(choices=[('Loam', 'Loam'), ('Clay', 'Clay'), ('Sandy', 'Sandy'), ('Silt', 'Silt'), ('Peaty', 'Peaty'), ('Chalky', 'Chalky')], default='Loam', max_length=20),
        ),
        migrations.AddField(
            model_name='land',
            name='water_source',
            field=models.CharField(choices=[('Well', 'Well'), ('River', 'River'), ('Rain', 'Rain'), ('Canal', 'Canal'), ('Municipal', 'Municipal'), ('None', 'None')], default='Well', max_length=20),
        ),
        migrations.AlterField(
            model_name='land',
            name='size',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Size in acres', max_digits=10),
        ),
    ]
